### ISSUE TITLE
Docker Hub passwords are stored plain text

### ISSUE THREAD

**Issue by sirodoht** [swarmpit/swarmpit#335]
BUG REPORT
------------------------

**Description**

If a user links the Docker Hub registry then their credentials are stored plain text in the CouchDB database. Of course this database is not exposed to then internet, but it is a security risk nonetheless.

**Steps to reproduce the issue:**
1. Link a Docker Hub registry using your account
2. Inspect the CouchDB database documents

**What happens:**

Notice your precious secret password in plain text form.

**What should happen:**

The encrypted password (or other way of authentication) should have remained unnoticed.

**Comment by nohaapav** [comment]
The thing is: If i get access to your infra i can easily run smth similar like:
`sudo security find-internet-password -gs hub.docker.com` to get you password,
because you did `docker login` at some point, even though docker is storing passwords in credentials helper nowadays :)

We can of course encrypt the password with some key, anyway i guess if you're attacker with access to infra this is just minor obstacle to deal with.

**Comment by nohaapav** [comment]
Basically all these systems like `1Password`, `Keychain` etc are just encrypted db full of credentials and if root/master password is going to leak you're in a pickle. :) Our premise here is that this ultimate root/master password is the access one to cluster.
