### ISSUE TITLE
Healthcheck - composer

### ISSUE THREAD

**Issue by mosonyi** [swarmpit/swarmpit#346]
**Description**
I am able to deploy a yml file into stack  and it is working fine.
```
version '3.4'
...
    healthcheck:
      test: curl --fail -s http://localhost/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
...
```

When I would like to retrieve  the **current engine state**, it always returns as
version '3.3' and **_no healthcheck included_**.

**Expected operation:**
I expect to get back everything what I have added before (including the verision 3.4).

**Workaround:**
Retrive the last deployed version, but it could cause a problem, if you have changed something meanwhile (ex: edit properties) on the UI.

At the moment if I edit seomthing on the UI I am changing my external composer file as well, which is not so efficient. I would appreciate if this could be fixed.

Thank you very much for your effort guys, this is a wonderful application!

Regards

Zoltan

**Comment by fxdgear** [comment]
I’m running into this issue as well. Cause when I try to deploy a stack which has 2 services using the same container but the second overrides the command, I get unhealthy services when I deploy updated stacks, as a result my second service never stays up cause of a faulty health check. 

This bug is more severe than I think initially reported.

**Comment by fxdgear** [comment]
to add a bit more detail here what' i've been noticing. 

I have a `web` container which runs gunicorn and the healthcheck that's defined in the container is `curl loclahosthost`. 

I use the same container to run some async workers cause they use the same code, I just override the `cmd` and the `healthcheck`. because, the swarmpit stack composer can't pick up the healtcheck, it defaults back to the one defined in the container and that is why all my `worker` nodes never turn green. 

I'm happy to see this is added to the 1.7 release! I'll be anxiously waiting! :smile:
