### ISSUE TITLE
login send empty json to server

### ISSUE THREAD

**Issue by Sherlock-Holo** [swarmpit/swarmpit#362]
**Description**

**Steps to reproduce the issue:**
1. deploy with manual install in docker swarm manager node
2. login http://10.20.30.16:888/#/login with admin admin

**What happens:**
report report The username or password you entered is incorrect.

use chrome F12 see send `null` json to server

**What should happen:**
send correct json to server

**Additional information (e.g. docker version, cluster setup,...):**
![image](https://user-images.githubusercontent.com/10096425/58966838-9810a900-87e5-11e9-8da8-7f2665c6c490.png)

**Comment by nohaapav** [comment]
Empty your cache or try with browser incognito mode .. Probably something is wrong on your side.

Request payload `null` is OK because there is none. Credential are sent in `Authorization` header as basic token ..

**Comment by Sherlock-Holo** [comment]
however I install latest,1.6 1.5 with mammal install, the default password
is incorrect

Pavol Noha <notifications@github.com> 于 2019年6月5日周三 23:45写道：

**Comment by nohaapav** [comment]
Obviously it is not. Try to drop swarmpit token from local storage and clear caches plus check if your database volume didn't change.

Password is working just fine.

**Comment by Sherlock-Holo** [comment]
I clean local storage and cache, but it still login failed

Pavol Noha <notifications@github.com> 于 2019年6月6日周四 15:58写道：

**Comment by nohaapav** [comment]
Are you sure that your db local volume is fine ? You can expose db port and take a look .. 

http://{your_ip}:5984/_utils/#database/swarmpit/_all_docs

**Comment by IlyasDeckers** [comment]
I had a similar issue yesterday. Removing the admin user from the DB through the UI, after exposing the management port, solved this issue. After deleting the user you get prompted to create a new user when visiting the login page.

Still, don't know what caused the issue, but it happened after the swarm cluster went down due to network issues at DigitalOcean.

**Comment by Wiklem** [comment]
Got this a bit to much to :/

**Comment by nohaapav** [comment]
The logic is following: If you don't have any user yet and your local storage has no token then force user to create new one.

If Swarmpit can't verify your identity following might be happening:
1) networking issues
2) your local storage was somehow corrupted
3) swarmpit db has been redeployed to different node but volume stays on the old one

Check if any of these are true. I suggest you to use shared volume driver in order to prevent such issues.
