### ISSUE TITLE
Services with IPv6

### ISSUE THREAD

**Issue by ekifox** [swarmpit/swarmpit#410]
I have only one ipv4 address and millions of possible combinations of ipv6 addresses because the provider gives me a /64 subnet.
I need to run multiple application replicas at different addresses and with one port. How to do it through swarmpit? You can add the possibility to use the ipv6 public network?

Example with nginx service:
Replica1: [::1]:8000
Replica2: [::2]:8000

**Comment by nohaapav** [comment]
Could you be more specific what you're trying to achieve ? 
You want to run multiple replicas of 1 service in swarm where service is published within same port ?

**Comment by ekifox** [comment]
@nohaapav Sorry to mislead you. The main question: how to create a service with a unique IPv6 address? So far I have only seen host port, container port in your panel, but where is host IP?

Another question, do you ever think to add a view of individual containers running in docker nodes?

**Comment by nohaapav** [comment]
@ekifox 
ad1) Well all services in swarm have basically unique ip .. Either in bridge or overlay network (private) .. Not really sure what is your goal here. Host IP is always the same and it's cluster node (VM) address. This one is unique per node. So let's say you have 4 nodes in cluster -> you got 4 different IP's but from each but you can access your service running on whatever node (routing mesh/balancing). This is how swarm is designed. You don't have to really care of your replica ip's because swarm will assign them some private ones.

ad2) Maybe in R/O mode.

**Comment by ekifox** [comment]
I can’t open the public port on the ipv6 address I specified.

**Comment by nohaapav** [comment]
Your application replicas are going to run in some private network .. So why don't you create overlay network with ipv6 enabled and then add your service in that network and publish port ?
