### ISSUE TITLE
improve hashing performance on arm cpu

### ISSUE THREAD

**Issue by lumir-mrkva** [swarmpit/swarmpit#425]

**Comment by nicholaspearson** [comment]
Hey, @lumir-mrkva is there an ETA on this? :)

**Comment by nohaapav** [comment]
@nicholaspearson It's going to be part of 1.9 release so mid January at the latest. We have to test few algorithms on ARM to see what is the best fit. Hashing support is already in place, now just figure out "the best buy for best price" ..

**Comment by YasserAntonio** [comment]
Hello, how long it should take on a rasp 3 to setup the admin account since the password is hashed with this new algorithme ? Asking  this because I'm waiting since 5 minutes and I still get a bad getaway when I refresh the page after setting the admin account. I want to be sure what's the corresponding normal time for this task to be done.
