### ISSUE TITLE
Will this project continue?

### ISSUE THREAD

**Issue by dhpowrhost** [swarmpit/swarmpit#451]
In light of the news that docker has been bought by Miratis who eventually will phase out swarm i would like to know how developers of this project tackle this situation. Will development to this project cease?

**Comment by nohaapav** [comment]
@dhpowrhost Well only docker EE business has been sold to Mirantis. Docker still keeps desktop, hub, machine, compose, swarm, ... Docker Swarm is OS project so even if the Docker stops development, support can live within the community. We choose this orchestrator because it's easy to learn and nearly all features can be understood by average developer in a full day class. We believe that in the ERA of rapid development, prototyping, startups such orchestrator is essential. It's still second largest on market and Docker will be stupid to shut it down entirely. And if they do so, new one following the same goal (simplicity) will find the way to shine. 

So to your question: Nope, we're not closing the project.

**Comment by dhpowrhost** [comment]
Thank you for the prompt answer and elaboration. I am not sure i understand the acquisition the same way as you do. I am sure you have more information than i do, but i did read that the acquisition also included swarm and core docker components. cf. https://thenewstack.io/mirantis-acquires-docker-enterprise/
