### ISSUE TITLE
Metadata for Disk info and IP - reporting wrong info

### ISSUE THREAD

**Issue by iangregsondev** [swarmpit/swarmpit#561]
Hi,

Can you tell me where the IP info comes from as one of mode node shows 0.0.0.0

And both nodes have 2 disks...

1. main disk where OS is installed is 500GB
2. Another disk I use for glusterfs which is 1TB

1 node shows the 500GB and the other node shows the 1TB.

Any ideas how I can go about fixing this ?

Heres a screenshot to explain it better

![image](https://user-images.githubusercontent.com/2370364/94352295-52739180-0063-11eb-9264-c39d5cdb60de.png)

**Comment by iangregsondev** [comment]
Good news is that the IP has fixed itself :-)

BUT - the disks are still reporting the wrong info, what should be reported here ?  My main disk (the 500GB)? or my extra disk(1TB) - or a sum of both?

![image](https://user-images.githubusercontent.com/2370364/94360362-f0d81500-00ac-11eb-9b58-0f9ed849e3e6.png)

**Comment by nohaapav** [comment]
Ad IP: It's because leader has been changed most probably. We track the issue with ip [here](https://github.com/swarmpit/swarmpit/issues/476). Will be fixed in upcoming release.

Ad Disk: Statistics are sent from agent which monitor only root partition. See following issues:

https://github.com/swarmpit/agent/issues/5
https://github.com/swarmpit/swarmpit/issues/394

Unfortunately we didn't have time to fix it yet. So still in the pipeline.

**Comment by lumir-mrkva** [comment]
closing in favor of #394
